// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9ms0MFVvXmgMpe3Tq_WVAuWdZKlKhb-g',
    appId: '1:812210093339:android:8db4647030b7c9754b27be',
    messagingSenderId: '812210093339',
    projectId: 'tienda3-3d9da',
    databaseURL: 'https://tienda3-3d9da-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tienda3-3d9da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEgWKX5NKy2UaHtu6UkJGB8-mYpS3ItJ4',
    appId: '1:812210093339:ios:6de8c55aa99317304b27be',
    messagingSenderId: '812210093339',
    projectId: 'tienda3-3d9da',
    databaseURL: 'https://tienda3-3d9da-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tienda3-3d9da.appspot.com',
    iosBundleId: 'com.example.tienda3Admin',
  );
}
